### ISSUE TITLE
timezone request  denied

### ISSUE THREAD

**Issue by sledgeh** [googlemaps/google-maps-services-python#149]
```
gmaps = googlemaps.Client(key='hidden key')
geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')  ##Works fine
tz = gmaps.timezone((40.714224, -73.961452))
```

```
Traceback (most recent call last):
  File "mapa.py", line 18, in <module>
    tz = gmaps.timezone((40.714224, -73.961452))
  File "C:\devel\Python27\lib\site-packages\googlemaps\timezone.py", line 54, in timezone
    return client._get( "/maps/api/timezone/json", params)
  File "C:\devel\Python27\lib\site-packages\googlemaps\client.py", line 240, in _get
    result = self._get_body(resp)
  File "C:\devel\Python27\lib\site-packages\googlemaps\client.py", line 265, in _get_body
    raise googlemaps.exceptions.ApiError(api_status)
googlemaps.exceptions.ApiError: REQUEST_DENIED
```

**Comment by sledgeh** [comment]
It could be [because ](https://developers.google.com/maps/documentation/timezone/intro)

> ### Important: You must submit requests via https, not http.

**Comment by stephenmcd** [comment]
Make sure you've enabled the timezone API in the developer console:

console.developers.google.com

**Comment by sledgeh** [comment]
Your right. Thanks
