### ISSUE TITLE
Breaks in Python 2.7

### ISSUE THREAD

**Issue by arita37** [googlemaps/google-maps-services-python#165]
When testing sample code, I have this message :

gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')
Traceback (most recent call last):

```
  File "<ipython-input-40-6caf8aba9b95>", line 1, in <module>
    gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')

  File "G:\_dev\anaconda27\lib\site-packages\googlemaps\client.py", line 337, in wrapper
    result = func(*args, **kwargs)

  File "G:\_dev\anaconda27\lib\site-packages\googlemaps\geocoding.py", line 68, in geocode
    return client._get("/maps/api/geocode/json", params)["results"]

  File "G:\_dev\anaconda27\lib\site-packages\googlemaps\client.py", line 223, in _get
    raise googlemaps.exceptions.TransportError(e)

TransportError: No module named uts46data
```

I have already isdna installed on Python 2.7, Win64bits, Anaconda

**Comment by stephenmcd** [comment]
Looks to be a requests issue as reported here:

https://github.com/kennethreitz/requests/issues/3818
