### ISSUE TITLE
pip3 installation fails.

### ISSUE THREAD

**Issue by Arkenan** [googlemaps/google-maps-services-python#183]
Hello!

I tried installing the googlemaps python client with the following bash instruction: 

```bash
sudo -H pip3 install -U googlemaps
``` 
and it failed with the following message:

```
Collecting googlemaps
  Using cached googlemaps-2.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no files found matching 'NOTICE'
    
    Installed /tmp/pip-build-nofkk50k/googlemaps/.eggs/requests-2.18.1-py3.5.egg
    Searching for certifi>=2017.4.17
    Reading https://pypi.python.org/simple/certifi/
    Downloading https://pypi.python.org/packages/dd/0e/1e3b58c861d40a9ca2d7ea4ccf47271d4456ae4294c5998ad817bd1b4396/certifi-2017.4.17.tar.gz#md5=db40445044feda1437ce3ccd5fc28a57
    Best match: certifi 2017.4.17
    Processing certifi-2017.4.17.tar.gz
    Writing /tmp/easy_install-86uu2ubw/certifi-2017.4.17/setup.cfg
    Running certifi-2017.4.17/setup.py -q bdist_egg --dist-dir /tmp/easy_install-86uu2ubw/certifi-2017.4.17/egg-dist-tmp-u20gfdhi
    /usr/local/lib/python3.5/dist-packages/setuptools/dist.py:333: UserWarning: Normalizing '2017.04.17' to '2017.4.17'
      normalized_version,
    zip_safe flag not set; analyzing archive contents...
    certifi.__pycache__.core.cpython-35: module references __file__
    creating /tmp/pip-build-nofkk50k/googlemaps/.eggs/certifi-2017.4.17-py3.5.egg
    Extracting certifi-2017.4.17-py3.5.egg to /tmp/pip-build-nofkk50k/googlemaps/.eggs
    
    Installed /tmp/pip-build-nofkk50k/googlemaps/.eggs/certifi-2017.4.17-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nofkk50k/googlemaps/setup.py", line 39, in <module>
        'Topic :: Internet',
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1116, in best_match
        dist = working_set.find(req)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 714, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (urllib3 1.13.1 (/usr/lib/python3/dist-packages), Requirement.parse('urllib3<1.22,>=1.21.1'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nofkk50k/googlemaps/

```

My attention is particularly drawn to the _"no files matching 'NOTICE'"_ line. Is this a bug or is this caused by the way i'm installing it?

I tried it in two different computers, both with xUbuntu 16.04, and python 3.5.3, working with anaconda, with the same results.

When installing the pip2 version of googlemaps with the same arguments, there were no errors. 

In both of them I ended up installing the module successfully by cloning the repo and using the setup.py file.

**Comment by stephenmcd** [comment]
This appears to be either an issue with the dependencies (`urllib3`, `chardet`) of this library's dependency (`requests`), or `pip` itself, and `requests` requiring specific versions when earlier versions already exist on the system. 

I can't say why `pip` fails to upgrade these when installing `googlemaps`, but I was able to reproduce the problem and resolve it by manually upgrading those dependencies myself by running `pip3 install -U urllib3 chardet`.

**Comment by katchu11** [comment]
Thank you!

This solved it for me!
