### ISSUE TITLE
TypeError: Expected a lat/lng dict or tuple, but got float

### ISSUE THREAD

**Issue by KobaKhit** [googlemaps/google-maps-services-python#206]
Hello,
I am using the google distance matrix api to get info for a list of 100k zipcodes. At about 15k I get this error. I am not sure how to remedy it. Any ideas? Thanks.

```python
Traceback (most recent call last):
  File "gmaps.py", line 81, in <module>
    main()
  File "gmaps.py", line 51, in main
    departure_time=now)
  File "C:\Users\kkhitalishvili\AppData\Local\Continuum\Anaconda3\lib\site-packages\googlemaps\client.py", line 356, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\kkhitalishvili\AppData\Local\Continuum\Anaconda3\lib\site-packages\googlemaps\distance_matrix.py", line 89, in distance_matrix
    "origins": convert.location_list(origins),
  File "C:\Users\kkhitalishvili\AppData\Local\Continuum\Anaconda3\lib\site-packages\googlemaps\convert.py", line 128, in location_list
    return "|".join([latlng(location) for location in as_list(arg)])
  File "C:\Users\kkhitalishvili\AppData\Local\Continuum\Anaconda3\lib\site-packages\googlemaps\convert.py", line 128, in <listcomp>
    return "|".join([latlng(location) for location in as_list(arg)])
  File "C:\Users\kkhitalishvili\AppData\Local\Continuum\Anaconda3\lib\site-packages\googlemaps\convert.py", line 79, in latlng

    normalized = normalize_lat_lng(arg)
  File "C:\Users\kkhitalishvili\AppData\Local\Continuum\Anaconda3\lib\site-packages\googlemaps\convert.py", line 107, in normalize_lat_lng
    "but got %s" % type(arg).__name__)
TypeError: Expected a lat/lng dict or tuple, but got float
```

**Comment by stephenmcd** [comment]
According to the docs the locations must be *an address, latitude/longitude coordinates, or a place ID*.

https://developers.google.com/maps/documentation/distance-matrix/intro

**Comment by Ishant27** [comment]
@stephenmcd ,
Yes, understood that according to docs locations must be an either one of the format mentioned above.But my question is then why the distance matrix api is giving result for some of the zipcode considering the input zipcode is not in the required format.
