### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by castorgit** [googlemaps/google-maps-services-python#219]
trying standard example: 
""
import googlemaps
from datetime import datetime
gmaps = googlemaps.Client(key='MyKey')

(I have a real API Key) but executing this 3 lines of code I get following error in adapters.py

TypeError: super(type, obj): obj must be an instance or subtype of type

Environment
Anaconda-Spyder (Python 3.6)

Thanks

**Comment by castorgit** [comment]
runfile('C:/Tesis/Programas/$NREL/dummy.py', wdir='C:/Tesis/Programas/$NREL')
Traceback (most recent call last):

  File "<ipython-input-22-d79869cb9881>", line 1, in <module>
    runfile('C:/Tesis/Programas/$NREL/dummy.py', wdir='C:/Tesis/Programas/$NREL')

  File "C:\Users\Manero\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Manero\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Tesis/Programas/$NREL/dummy.py", line 12, in <module>
    gmaps = googlemaps.Client(key='XXXXXXXXXXXXXXX')

  File "C:\Users\Manero\Anaconda3\lib\site-packages\googlemaps\client.py", line 124, in __init__
    self.session = requests.Session()

  File "C:\Users\Manero\Anaconda3\lib\site-packages\requests\sessions.py", line 392, in __init__
    self.mount('https://', HTTPAdapter())

  File "C:\Users\Manero\Anaconda3\lib\site-packages\requests\adapters.py", line 120, in __init__
    super(HTTPAdapter, self).__init__()

TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by castorgit** [comment]
error solved. thanks

**Comment by cheriemilk** [comment]
Hi castorgit,
how do you resolve tihs?
