### ISSUE TITLE
request entity not found error

### ISSUE THREAD

**Issue by arashtavakoli** [googlemaps/google-maps-services-python#387]
Hi,

I am trying to use this implementation on some basic lat,long data and whatever I try I receive the same error. I am sure emy KEY is correct. I cannot see why this does not return the values request:
code:
import googlemaps
from datetime import datetime

KEY = 'XXXXXXXXXX'
gmaps = googlemaps.Client(key= KEY)

latlng = [(38.9025366,-77.4546587),(38.9024659,-77.4548784),(38.8833746,-77.406403),(38.8647126,-77.4066174),(38.8647744,-77.406645),(38.8647744,-77.406645),(38.922426,-77.4128883)]

results = gmaps.snap_to_roads(latlng)

results_latlng = []
for dicts in results:
	location = dicts['location']
	lat = location['latitude']
	lon = location['longitude']
	latlngtuple = (lat,lon)
	results_latlng.append(latlngtuple)

print(results_latlng)
#print(results)

Errors:
Traceback (most recent call last):
  File "D:\Google Drive\UVA_PhD\Projects\Similar trips from GPS\snaproads.py", line 11, in <module>
    results = gmaps.snap_to_roads(latlng)
  File "C:\Program Files\Python\lib\site-packages\googlemaps\client.py", line 418, in wrapper
    result = func(*args, **kwargs)
  File "C:\Program Files\Python\lib\site-packages\googlemaps\roads.py", line 56, in snap_to_roads
    extract_body=_roads_extract).get("snappedPoints", [])
  File "C:\Program Files\Python\lib\site-packages\googlemaps\client.py", line 311, in _request
    result = extract_body(response)
  File "C:\Program Files\Python\lib\site-packages\googlemaps\roads.py", line 139, in _roads_extract
    raise googlemaps.exceptions.ApiError(status, error.get("message"))
googlemaps.exceptions.ApiError: NOT_FOUND (Requested entity was not found.)

**Comment by jpoehnelt** [comment]
Might need a billing acount? https://stackoverflow.com/questions/58522273/google-roads-api-requested-entity-was-not-found
