### ISSUE TITLE
Logging trouble

### ISSUE THREAD

**Issue by benoit9126** [googlemaps/google-maps-services-python#458]
Hi,
My problem comes from a change from #451. Currently, this [line](https://github.com/googlemaps/google-maps-services-python/blob/c5982e7eadd8ded7bfcef862fa6182516125d19b/googlemaps/client.py#L194) fails because `self.queries_quota` is an `int` and not a string.

#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...") -> All API
2. OS type and version: 
  ```bash
  uname -a
  # Linux mirabelle 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

  python -VV
  # Python 3.10.7 (main, Oct  3 2022, 15:46:37) [GCC 10.2.1 20210110]
  ```
4. Library version and other environment information -> Version 4.7.2

#### Code example

```python
import googlemaps
googlemaps.Client(key="AIzaMOCK")
```

#### Stack trace

```
Traceback (most recent call last):
  File "/home/benoit/.pyenv/versions/sirao_api/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-1868f35d3166>", line 1, in <module>
    googlemaps.Client(key="AIzaMOCK")
  File "/home/benoit/.pyenv/versions/3.10.7/envs/sirao_api/lib/python3.10/site-packages/googlemaps/client.py", line 194, in __init__
    logger.info("API queries_quota:", self.queries_quota)
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/home/benoit/.pyenv/versions/3.10.7/envs/sirao_api/lib/python3.10/site-packages/rich/logging.py", line 128, in emit
    message = self.format(record)
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/home/benoit/.pyenv/versions/3.10.7/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by benoit9126** [comment]
Sorry: Duplicate of #456
